package com.help.finance_code.ui.transaction

import com.help.finance_code.data.Categoria
import java.util.Locale

object CategorySuggester {

    private val keywords: Map<String, String> = buildMap {
        put("salario", "Salario e Ingresos")
        put("sueldo", "Salario e Ingresos")
        put("quincena", "Salario e Ingresos")
        put("honorarios", "Salario e Ingresos")
        put("nomina", "Salario e Ingresos")
        put("pago nomina", "Salario e Ingresos")
        put("prima", "Salario e Ingresos")
        put("liquidacion", "Salario e Ingresos")
        put("cesantias", "Salario e Ingresos")
        put("mesada", "Salario e Ingresos")
        put("prestacion", "Salario e Ingresos")
        put("incapacidad", "Salario e Ingresos")
        put("venta", "Salario e Ingresos")
        put("negocio", "Salario e Ingresos")
        put("ganancia", "Salario e Ingresos")
        put("utilidad", "Salario e Ingresos")
        put("bono", "Salario e Ingresos")
        put("ingreso extra", "Salario e Ingresos")
        put("rebusque", "Salario e Ingresos")
        put("camello", "Salario e Ingresos")
        put("aguinaldo", "Salario e Ingresos")
        put("pension", "Salario e Ingresos")
        put("arriendo", "Salario e Ingresos")
        put("subsidio", "Salario e Ingresos")
        put("interes", "Salario e Ingresos")
        put("intereses", "Salario e Ingresos")
        put("abono interes", "Salario e Ingresos")
        put("pago de intereses", "Salario e Ingresos")
        put("rendimientos", "Salario e Ingresos")
        put("dividendo", "Salario e Ingresos")

        put("moto", "Motos")
        put("motocicleta", "Motos")
        put("yamaha", "Motos")
        put("suzuki", "Motos")
        put("honda", "Motos")
        put("kawasaki", "Motos")
        put("tvs", "Motos")
        put("bajaj", "Motos")
        put("hero", "Motos")
        put("kymco", "Motos")
        put("royal enfield", "Motos")
        put("ktm", "Motos")
        put("husqvarna", "Motos")
        put("benelli", "Motos")
        put("auteco", "Motos")
        put("victoria", "Motos")
        put("macarena", "Motos")
        put("sym", "Motos")
        put("akt", "Motos")
        put("fz", "Motos")
        put("gixxer", "Motos")
        put("raider", "Motos")
        put("apache", "Motos")
        put("ns 200", "Motos")
        put("ns 160", "Motos")
        put("pulsar", "Motos")
        put("dominar", "Motos")
        put("boxer", "Motos")
        put("nkd", "Motos")
        put("duke", "Motos")
        put("mt09", "Motos")
        put("mt07", "Motos")
        put("mt03", "Motos")
        put("r15", "Motos")
        put("dr650", "Motos")
        put("xr150", "Motos")
        put("xtz", "Motos")
        put("cb190", "Motos")
        put("cbr", "Motos")
        put("gn 125", "Motos")
        put("gs 125", "Motos")
        put("libero", "Motos")
        put("agility", "Motos")
        put("bws", "Motos")
        put("vstrom", "Motos")
        put("nmax", "Motos")
        put("xmax", "Motos")
        put("pcx", "Motos")
        put("himalayan", "Motos")
        put("meteor", "Motos")
        put("interceptor", "Motos")
        put("discover", "Motos")
        put("platino", "Motos")
        put("splendor", "Motos")
        put("casco", "Motos")
        put("impermeable", "Motos")
        put("rodilleras", "Motos")
        put("guantes moto", "Motos")
        put("shaaf", "Motos")
        put("ls2", "Motos")
        put("agv", "Motos")
        put("airoh", "Motos")
        put("nolan", "Motos")
        put("alpinestars", "Motos")
        put("maletero", "Motos")
        put("baul", "Motos")
        put("shad", "Motos")
        put("givi", "Motos")
        put("mundimotos", "Motos")
        put("motul", "Motos")
        put("mobil1", "Motos")

        put("carro", "Carros")
        put("coche", "Carros")
        put("automovil", "Carros")
        put("chevrolet", "Carros")
        put("renault", "Carros")
        put("mazda", "Carros")
        put("kia", "Carros")
        put("toyota", "Carros")
        put("nissan", "Carros")
        put("ford", "Carros")
        put("volkswagen", "Carros")
        put("hyundai", "Carros")
        put("jeep", "Carros")
        put("bmw", "Carros")
        put("audi", "Carros")
        put("mercedes", "Carros")
        put("peugeot", "Carros")
        put("volvo", "Carros")
        put("subaru", "Carros")
        put("seat", "Carros")
        put("fiat", "Carros")
        put("chery", "Carros")
        put("mg", "Carros")
        put("byd", "Carros")
        put("jac", "Carros")
        put("foton", "Carros")
        put("spark", "Carros")
        put("logan", "Carros")
        put("sandero", "Carros")
        put("picanto", "Carros")
        put("march", "Carros")
        put("twingo", "Carros")
        put("tracker", "Carros")
        put("duster", "Carros")
        put("cx5", "Carros")
        put("cx30", "Carros")
        put("mazda 3", "Carros")
        put("mazda 2", "Carros")
        put("prado", "Carros")
        put("txl", "Carros")
        put("fortuner", "Carros")
        put("hilux", "Carros")
        put("sail", "Carros")
        put("aveo", "Carros")
        put("beat", "Carros")
        put("cruze", "Carros")
        put("corolla", "Carros")
        put("stepway", "Carros")
        put("clio", "Carros")
        put("fiesta", "Carros")
        put("ecosport", "Carros")
        put("escape", "Carros")
        put("jetta", "Carros")
        put("gol", "Carros")
        put("sportage", "Carros")
        put("tucson", "Carros")
        put("rio", "Carros")
        put("cerato", "Carros")
        put("onix", "Carros")
        put("captiva", "Carros")
        put("kwid", "Carros")
        put("oroch", "Carros")
        put("koleos", "Carros")
        put("frontera", "Carros")

        put("reparacion", "Mantenimiento y Reparación")
        put("arreglo", "Mantenimiento y Reparación")
        put("repuestos", "Mantenimiento y Reparación")
        put("mecanico", "Mantenimiento y Reparación")
        put("taller", "Mantenimiento y Reparación")
        put("aceite", "Mantenimiento y Reparación")
        put("pastillas de freno", "Mantenimiento y Reparación")
        put("frenos", "Mantenimiento y Reparación")
        put("llantas", "Mantenimiento y Reparación")
        put("bateria", "Mantenimiento y Reparación")
        put("pintura", "Mantenimiento y Reparación")
        put("latoneria", "Mantenimiento y Reparación")
        put("despinche", "Mantenimiento y Reparación")
        put("sincronizacion", "Mantenimiento y Reparación")
        put("alineacion", "Mantenimiento y Reparación")
        put("balanceo", "Mantenimiento y Reparación")
        put("revision", "Mantenimiento y Reparación")
        put("tecnomecanica", "Mantenimiento y Reparación")
        put("mantenimiento", "Mantenimiento y Reparación")
        put("lavadero", "Mantenimiento y Reparación")
        put("montallantas", "Mantenimiento y Reparación")
        put("lubricentro", "Mantenimiento y Reparación")
        put("mofles", "Mantenimiento y Reparación")
        put("exosto", "Mantenimiento y Reparación")
        put("amortiguadores", "Mantenimiento y Reparación")
        put("plumillas", "Mantenimiento y Reparación")
        put("refrigerante", "Mantenimiento y Reparación")
        put("bateria mac", "Mantenimiento y Reparación")
        put("bateria duncan", "Mantenimiento y Reparación")
        put("varta", "Mantenimiento y Reparación")
        put("bosch", "Mantenimiento y Reparación")
        put("michelin", "Mantenimiento y Reparación")
        put("goodyear", "Mantenimiento y Reparación")
        put("pirelli", "Mantenimiento y Reparación")
        put("hankook", "Mantenimiento y Reparación")
        put("bridgestone", "Mantenimiento y Reparación")
        put("maxxis", "Mantenimiento y Reparación")

        put("bancolombia", "Bancos y Finanzas")
        put("davivienda", "Bancos y Finanzas")
        put("aval", "Bancos y Finanzas")
        put("bogota", "Bancos y Finanzas")
        put("occidente", "Bancos y Finanzas")
        put("popular", "Bancos y Finanzas")
        put("caja social", "Bancos y Finanzas")
        put("bbva", "Bancos y Finanzas")
        put("colpatria", "Bancos y Finanzas")
        put("nubank", "Bancos y Finanzas")
        put("lulo", "Bancos y Finanzas")
        put("dale", "Bancos y Finanzas")
        put("rappipay", "Bancos y Finanzas")
        put("uala", "Bancos y Finanzas")
        put("pibank", "Bancos y Finanzas")
        put("scotiabank", "Bancos y Finanzas")
        put("itau", "Bancos y Finanzas")
        put("pichincha", "Bancos y Finanzas")
        put("finandina", "Bancos y Finanzas")
        put("cotrafa", "Bancos y Finanzas")
        put("confiar", "Bancos y Finanzas")
        put("bancoomeva", "Bancos y Finanzas")
        put("serfinanza", "Bancos y Finanzas")
        put("wompi", "Bancos y Finanzas")
        put("epayco", "Bancos y Finanzas")
        put("payu", "Bancos y Finanzas")
        put("mercadopago", "Bancos y Finanzas")
        put("tarjeta de credito", "Bancos y Finanzas")
        put("tc", "Bancos y Finanzas")
        put("cuota de manejo", "Bancos y Finanzas")
        put("comision", "Bancos y Finanzas")
        put("prestamo", "Bancos y Finanzas")
        put("deuda", "Bancos y Finanzas")
        put("gota a gota", "Bancos y Finanzas")
        put("paga diario", "Bancos y Finanzas")
        put("fiado", "Bancos y Finanzas")
        put("sistecredito", "Bancos y Finanzas")
        put("ptm", "Bancos y Finanzas")
        put("credito", "Bancos y Finanzas")
        put("ahorro", "Bancos y Finanzas")
        put("inversion", "Bancos y Finanzas")
        put("cdt", "Bancos y Finanzas")
        put("4x1000", "Bancos y Finanzas")
        put("gravamen", "Bancos y Finanzas")
        put("sucursal virtual", "Bancos y Finanzas")
        put("cajero", "Bancos y Finanzas")
        put("atm", "Bancos y Finanzas")
        put("corresponsal", "Bancos y Finanzas")
        put("consig", "Bancos y Finanzas")
        put("consignacion", "Bancos y Finanzas")
        put("retiro", "Bancos y Finanzas")
        put("reverso", "Bancos y Finanzas")
        put("ajuste", "Bancos y Finanzas")
        put("iva", "Bancos y Finanzas")

        put("nequi", "Transferencias")
        put("daviplata", "Transferencias")
        put("transf", "Transferencias")
        put("transferencia", "Transferencias")
        put("pse", "Transferencias")
        put("bre-b", "Transferencias")
        put("cobre", "Transferencias")
        put("ach", "Transferencias")
        put("transfiya", "Transferencias")
        put("traspaso", "Transferencias")
        put("giro", "Transferencias")
        put("efecty", "Transferencias")
        put("supergiros", "Transferencias")
        put("western union", "Transferencias")
        put("moneygram", "Transferencias")

        put("mercado", "Supermercado")
        put("d1", "Supermercado")
        put("ara", "Supermercado")
        put("exito", "Supermercado")
        put("carulla", "Supermercado")
        put("jumbo", "Supermercado")
        put("makro", "Supermercado")
        put("olimpica", "Supermercado")
        put("alkosto", "Supermercado")
        put("surtimax", "Supermercado")
        put("isimo", "Supermercado")
        put("colsubsidio", "Supermercado")
        put("fruver", "Supermercado")
        put("corabastos", "Supermercado")
        put("mercaldas", "Supermercado")
        put("euro", "Supermercado")
        put("la 14", "Supermercado")
        put("megatienda", "Supermercado")
        put("zapatoca", "Supermercado")
        put("super inter", "Supermercado")
        put("price mart", "Supermercado")
        put("pricemart", "Supermercado")
        put("minimercado", "Supermercado")
        put("viveres", "Supermercado")
        put("tienda", "Supermercado")
        put("granero", "Supermercado")
        put("plaza de mercado", "Supermercado")
        put("paloquemao", "Supermercado")
        put("surtifruver", "Supermercado")
        put("carniceria", "Supermercado")
        put("fama", "Supermercado")
        put("cigarreria", "Supermercado")
        put("legumbreria", "Supermercado")

        put("restaurante", "Comida y Restaurantes")
        put("almuerzo", "Comida y Restaurantes")
        put("cena", "Comida y Restaurantes")
        put("desayuno", "Comida y Restaurantes")
        put("pizza", "Comida y Restaurantes")
        put("hamburguesa", "Comida y Restaurantes")
        put("empanada", "Comida y Restaurantes")
        put("asado", "Comida y Restaurantes")
        put("pollo", "Comida y Restaurantes")
        put("domicilio", "Comida y Restaurantes")
        put("rappi", "Comida y Restaurantes")
        put("tostao", "Comida y Restaurantes")
        put("crepes", "Comida y Restaurantes")
        put("kfc", "Comida y Restaurantes")
        put("mcdonalds", "Comida y Restaurantes")
        put("helado", "Comida y Restaurantes")
        put("frisby", "Comida y Restaurantes")
        put("el corral", "Comida y Restaurantes")
        put("subway", "Comida y Restaurantes")
        put("juan valdez", "Comida y Restaurantes")
        put("oma", "Comida y Restaurantes")
        put("panaderia", "Comida y Restaurantes")
        put("arepa", "Comida y Restaurantes")
        put("buñuelo", "Comida y Restaurantes")
        put("perro caliente", "Comida y Restaurantes")
        put("salchipapa", "Comida y Restaurantes")
        put("tamal", "Comida y Restaurantes")
        put("lechona", "Comida y Restaurantes")
        put("ajiaco", "Comida y Restaurantes")
        put("sancocho", "Comida y Restaurantes")
        put("bandeja paisa", "Comida y Restaurantes")
        put("viva la pi", "Comida y Restaurantes")
        put("kokoriko", "Comida y Restaurantes")
        put("presto", "Comida y Restaurantes")
        put("leños", "Comida y Restaurantes")
        put("hornitos", "Comida y Restaurantes")
        put("starbucks", "Comida y Restaurantes")
        put("wok", "Comida y Restaurantes")
        put("sipote", "Comida y Restaurantes")
        put("qbano", "Comida y Restaurantes")
        put("papa johns", "Comida y Restaurantes")
        put("burger king", "Comida y Restaurantes")
        put("krispy kreme", "Comida y Restaurantes")
        put("bbc", "Comida y Restaurantes")
        put("bogota beer", "Comida y Restaurantes")
        put("andres carne de res", "Comida y Restaurantes")
        put("andres dc", "Comida y Restaurantes")
        put("corral gourmet", "Comida y Restaurantes")
        put("mimos", "Comida y Restaurantes")
        put("pops", "Comida y Restaurantes")
        put("picos", "Comida y Restaurantes")
        put("empanadas tipicas", "Comida y Restaurantes")
        put("pan pa ya", "Comida y Restaurantes")
        put("comapan", "Comida y Restaurantes")
        put("asadero", "Comida y Restaurantes")
        put("piqueteadero", "Comida y Restaurantes")
        put("chuzo", "Comida y Restaurantes")
        put("chuzos", "Comida y Restaurantes")
        put("fritanga", "Comida y Restaurantes")
        put("mazorcada", "Comida y Restaurantes")
        put("picada", "Comida y Restaurantes")
        put("corrientazo", "Comida y Restaurantes")

        put("amazon", "Compras Online")
        put("temu", "Compras Online")
        put("aliexpress", "Compras Online")
        put("shein", "Compras Online")
        put("shopee", "Compras Online")
        put("mercadolibre", "Compras Online")
        put("falabella", "Compras Online")
        put("homecenter", "Compras Online")
        put("pagseguro", "Compras Online")
        put("target", "Compras Online")
        put("ebay", "Compras Online")
        put("wish", "Compras Online")
        put("linio", "Compras Online")
        put("dafiti", "Compras Online")
        put("exito.com", "Compras Online")
        put("tiendamia", "Compras Online")
        put("alibaba", "Compras Online")

        put("netflix", "Servicios Digitales")
        put("spotify", "Servicios Digitales")
        put("youtube", "Servicios Digitales")
        put("paypal", "Servicios Digitales")
        put("prime", "Servicios Digitales")
        put("disney", "Servicios Digitales")
        put("hbo", "Servicios Digitales")
        put("max", "Servicios Digitales")
        put("apple", "Servicios Digitales")
        put("google cloud", "Servicios Digitales")
        put("hostinger", "Servicios Digitales")
        put("ilovepdf", "Servicios Digitales")
        put("chatgpt", "Servicios Digitales")
        put("openai", "Servicios Digitales")
        put("midjourney", "Servicios Digitales")
        put("canva", "Servicios Digitales")
        put("adobe", "Servicios Digitales")
        put("aws", "Servicios Digitales")
        put("microsoft", "Servicios Digitales")
        put("godaddy", "Servicios Digitales")
        put("coursera", "Servicios Digitales")
        put("platzi", "Servicios Digitales")
        put("domestika", "Servicios Digitales")
        put("github", "Servicios Digitales")
        put("crunchyroll", "Servicios Digitales")
        put("paramount", "Servicios Digitales")
        put("icloud", "Servicios Digitales")
        put("dropbox", "Servicios Digitales")
        put("google one", "Servicios Digitales")
        put("vix", "Servicios Digitales")
        put("directv go", "Servicios Digitales")
        put("star plus", "Servicios Digitales")
        put("deezer", "Servicios Digitales")
        put("tidal", "Servicios Digitales")
        put("tinder", "Servicios Digitales")
        put("bumble", "Servicios Digitales")
        put("onlyfans", "Servicios Digitales")
        put("7151code", "Servicios Digitales")

        put("cine", "Cine y Entretenimiento")
        put("videojuegos", "Cine y Entretenimiento")
        put("play", "Cine y Entretenimiento")
        put("xbox", "Cine y Entretenimiento")
        put("steam", "Cine y Entretenimiento")
        put("playstation", "Cine y Entretenimiento")
        put("epic games", "Cine y Entretenimiento")
        put("ge force now", "Cine y Entretenimiento")
        put("apuestas", "Cine y Entretenimiento")
        put("casino", "Cine y Entretenimiento")
        put("baloto", "Cine y Entretenimiento")
        put("concierto", "Cine y Entretenimiento")
        put("billar", "Cine y Entretenimiento")
        put("tejo", "Cine y Entretenimiento")
        put("sintetica", "Cine y Entretenimiento")
        put("cancha sintetica", "Cine y Entretenimiento")
        put("futbol", "Cine y Entretenimiento")
        put("estadio", "Cine y Entretenimiento")
        put("cinecolombia", "Cine y Entretenimiento")
        put("cinemark", "Cine y Entretenimiento")
        put("procinal", "Cine y Entretenimiento")
        put("royal films", "Cine y Entretenimiento")
        put("nintendo", "Cine y Entretenimiento")
        put("blizzard", "Cine y Entretenimiento")
        put("riot", "Cine y Entretenimiento")
        put("ea", "Cine y Entretenimiento")
        put("ubisoft", "Cine y Entretenimiento")
        put("betplay", "Cine y Entretenimiento")
        put("wplay", "Cine y Entretenimiento")
        put("rushbet", "Cine y Entretenimiento")
        put("codere", "Cine y Entretenimiento")
        put("tuboleta", "Cine y Entretenimiento")
        put("taquilla", "Cine y Entretenimiento")
        put("eticket", "Cine y Entretenimiento")
        put("boliche", "Cine y Entretenimiento")
        put("bolos", "Cine y Entretenimiento")
        put("parque de diversiones", "Cine y Entretenimiento")
        put("salitre magico", "Cine y Entretenimiento")
        put("mundo aventura", "Cine y Entretenimiento")
        put("divercity", "Cine y Entretenimiento")
        put("playland", "Cine y Entretenimiento")

        put("gasolina", "Vehículo y Gasolina")
        put("tanqueo", "Vehículo y Gasolina")
        put("parqueadero", "Vehículo y Gasolina")
        put("peaje", "Vehículo y Gasolina")
        put("soat", "Vehículo y Gasolina")
        put("acpm", "Vehículo y Gasolina")
        put("estacion d", "Vehículo y Gasolina")
        put("eds ", "Vehículo y Gasolina")
        put("texaco", "Vehículo y Gasolina")
        put("terpel", "Vehículo y Gasolina")
        put("primax", "Vehículo y Gasolina")
        put("esso", "Vehículo y Gasolina")
        put("mobil", "Vehículo y Gasolina")
        put("petrobras", "Vehículo y Gasolina")
        put("chevron", "Vehículo y Gasolina")
        put("zeuss", "Vehículo y Gasolina")
        put("briq", "Vehículo y Gasolina")
        put("biomax", "Vehículo y Gasolina")
        put("estacion de servicio", "Vehículo y Gasolina")
        put("combustible", "Vehículo y Gasolina")
        put("parqueo", "Vehículo y Gasolina")
        put("valet", "Vehículo y Gasolina")

        put("bus", "Transporte Público")
        put("transmilenio", "Transporte Público")
        put("pasaje", "Transporte Público")
        put("sitp", "Transporte Público")
        put("taxi", "Transporte Público")
        put("uber", "Transporte Público")
        put("didi", "Transporte Público")
        put("cabify", "Transporte Público")
        put("picap", "Transporte Público")
        put("indriver", "Transporte Público")
        put("metro", "Transporte Público")
        put("mio", "Transporte Público")
        put("alimentador", "Transporte Público")
        put("flota", "Transporte Público")
        put("transmetro", "Transporte Público")
        put("megabus", "Transporte Público")
        put("metrolinea", "Transporte Público")
        put("transcaribe", "Transporte Público")
        put("terminal", "Transporte Público")
        put("tiquete", "Transporte Público")
        put("chaleco", "Transporte Público")
        put("bicitaxi", "Transporte Público")
        put("colectivo", "Transporte Público")

        put("farmacia", "Salud y Farmacia")
        put("medico", "Salud y Farmacia")
        put("pastillas", "Salud y Farmacia")
        put("eps", "Salud y Farmacia")
        put("cita medica", "Salud y Farmacia")
        put("urgencias", "Salud y Farmacia")
        put("condones", "Salud y Farmacia")
        put("preservativos", "Salud y Farmacia")
        put("drogueria", "Salud y Farmacia")
        put("odontologo", "Salud y Farmacia")
        put("dentista", "Salud y Farmacia")
        put("psicologo", "Salud y Farmacia")
        put("terapia", "Salud y Farmacia")
        put("cruz verde", "Salud y Farmacia")
        put("farmatodo", "Salud y Farmacia")
        put("colsanitas", "Salud y Farmacia")
        put("sura", "Salud y Farmacia")
        put("sanitas", "Salud y Farmacia")
        put("famisanar", "Salud y Farmacia")
        put("compensar", "Salud y Farmacia")
        put("la rebaja", "Salud y Farmacia")
        put("pasteur", "Salud y Farmacia")
        put("copidrogas", "Salud y Farmacia")
        put("salud total", "Salud y Farmacia")
        put("nueva eps", "Salud y Farmacia")
        put("asmet", "Salud y Farmacia")
        put("coosalud", "Salud y Farmacia")
        put("hospital", "Salud y Farmacia")
        put("clinica", "Salud y Farmacia")
        put("optica", "Salud y Farmacia")
        put("laboratorio", "Salud y Farmacia")
        put("profamilia", "Salud y Farmacia")
        put("idime", "Salud y Farmacia")
        put("colsubsidio salud", "Salud y Farmacia")
        put("medicina prepagada", "Salud y Farmacia")
        put("examen", "Salud y Farmacia")

        put("arriendo", "Hogar y Servicios")
        put("agua", "Hogar y Servicios")
        put("luz", "Hogar y Servicios")
        put("gas", "Hogar y Servicios")
        put("internet", "Hogar y Servicios")
        put("claro", "Hogar y Servicios")
        put("movistar", "Hogar y Servicios")
        put("celular", "Hogar y Servicios")
        put("plan", "Hogar y Servicios")
        put("recarga", "Hogar y Servicios")
        put("administracion", "Hogar y Servicios")
        put("aseo", "Hogar y Servicios")
        put("ferreteria", "Hogar y Servicios")
        put("wom", "Hogar y Servicios")
        put("etb", "Hogar y Servicios")
        put("tigo", "Hogar y Servicios")
        put("directv", "Hogar y Servicios")
        put("vanti", "Hogar y Servicios")
        put("epm", "Hogar y Servicios")
        put("enel", "Hogar y Servicios")
        put("codensa", "Hogar y Servicios")
        put("gases del caribe", "Hogar y Servicios")
        put("triple a", "Hogar y Servicios")
        put("acueducto", "Hogar y Servicios")
        put("emcali", "Hogar y Servicios")
        put("afinia", "Hogar y Servicios")
        put("electricaribe", "Hogar y Servicios")
        put("aire", "Hogar y Servicios")
        put("alquiler", "Hogar y Servicios")
        put("plomero", "Hogar y Servicios")
        put("cerrajero", "Hogar y Servicios")
        put("electricista", "Hogar y Servicios")
        put("easy", "Hogar y Servicios")
        put("constructor", "Hogar y Servicios")
        put("muebles", "Hogar y Servicios")
        put("jamar", "Hogar y Servicios")
        put("tugo", "Hogar y Servicios")

        put("ropa", "Ropa y Cuidado")
        put("zapatos", "Ropa y Cuidado")
        put("tenis", "Ropa y Cuidado")
        put("chaqueta", "Ropa y Cuidado")
        put("pantalon", "Ropa y Cuidado")
        put("camisa", "Ropa y Cuidado")
        put("centro comercial", "Ropa y Cuidado")
        put("maquillaje", "Ropa y Cuidado")
        put("barberia", "Ropa y Cuidado")
        put("peluqueria", "Ropa y Cuidado")
        put("uñas", "Ropa y Cuidado")
        put("perfume", "Ropa y Cuidado")
        put("zara", "Ropa y Cuidado")
        put("bershka", "Ropa y Cuidado")
        put("h&m", "Ropa y Cuidado")
        put("koaj", "Ropa y Cuidado")
        put("gef", "Ropa y Cuidado")
        put("punto blanco", "Ropa y Cuidado")
        put("arturo calle", "Ropa y Cuidado")
        put("cuidado personal", "Ropa y Cuidado")
        put("skincare", "Ropa y Cuidado")
        put("pull&bear", "Ropa y Cuidado")
        put("stradivarius", "Ropa y Cuidado")
        put("studio f", "Ropa y Cuidado")
        put("ela", "Ropa y Cuidado")
        put("patprimo", "Ropa y Cuidado")
        put("facol", "Ropa y Cuidado")
        put("totto", "Ropa y Cuidado")
        put("velez", "Ropa y Cuidado")
        put("chevignon", "Ropa y Cuidado")
        put("naf naf", "Ropa y Cuidado")
        put("americanino", "Ropa y Cuidado")
        put("levis", "Ropa y Cuidado")
        put("diesel", "Ropa y Cuidado")
        put("nike", "Ropa y Cuidado")
        put("adidas", "Ropa y Cuidado")
        put("puma", "Ropa y Cuidado")
        put("reebok", "Ropa y Cuidado")
        put("under armour", "Ropa y Cuidado")
        put("mac", "Ropa y Cuidado")
        put("miniso", "Ropa y Cuidado")
        put("dollarcity", "Ropa y Cuidado")
        put("victoria secret", "Ropa y Cuidado")
        put("bata", "Ropa y Cuidado")
        put("crocs", "Ropa y Cuidado")
        put("santodomingo", "Ropa y Cuidado")
        put("san andresito", "Ropa y Cuidado")
        put("el gran san", "Ropa y Cuidado")
        put("victorinos", "Ropa y Cuidado")
        put("bosi", "Ropa y Cuidado")
        put("epk", "Ropa y Cuidado")
        put("offcorss", "Ropa y Cuidado")
        put("spring step", "Ropa y Cuidado")
        put("payless", "Ropa y Cuidado")

        put("universidad", "Educación")
        put("semestre", "Educación")
        put("cuadernos", "Educación")
        put("fotocopias", "Educación")
        put("libros", "Educación")
        put("pension", "Educación")
        put("colegio", "Educación")
        put("utiles", "Educación")
        put("matricula", "Educación")
        put("curso", "Educación")
        put("sena", "Educación")
        put("instituto", "Educación")
        put("diplomado", "Educación")
        put("panamericana", "Educación")
        put("papeleria", "Educación")
        put("nacional", "Educación")
        put("udea", "Educación")
        put("unal", "Educación")
        put("javeriana", "Educación")
        put("los andes", "Educación")
        put("rosario", "Educación")
        put("externado", "Educación")
        put("sabana", "Educación")
        put("eafit", "Educación")
        put("univalle", "Educación")
        put("uis", "Educación")
        put("escolar", "Educación")
        put("jardin", "Educación")
        put("guarderia", "Educación")
        put("ruta escolar", "Educación")

        put("perro", "Mascotas")
        put("gato", "Mascotas")
        put("veterinario", "Mascotas")
        put("purina", "Mascotas")
        put("concentrado", "Mascotas")
        put("croquetas", "Mascotas")
        put("mascota", "Mascotas")
        put("arena", "Mascotas")
        put("agrocampo", "Mascotas")
        put("tierragro", "Mascotas")
        put("pet", "Mascotas")
        put("petshop", "Mascotas")
        put("laika", "Mascotas")
        put("kanu", "Mascotas")
        put("chunky", "Mascotas")
        put("dog chow", "Mascotas")
        put("cat chow", "Mascotas")
        put("bravecto", "Mascotas")
        put("nexgard", "Mascotas")
        put("peluqueria canina", "Mascotas")
        put("guarderia canina", "Mascotas")

        put("vuelo", "Viajes")
        put("avion", "Viajes")
        put("hotel", "Viajes")
        put("viaje", "Viajes")
        put("vacaciones", "Viajes")
        put("turismo", "Viajes")
        put("airbnb", "Viajes")
        put("pasajes", "Viajes")
        put("avianca", "Viajes")
        put("latam", "Viajes")
        put("wingo", "Viajes")
        put("satena", "Viajes")
        put("copa", "Viajes")
        put("jetmart", "Viajes")
        put("clic", "Viajes")
        put("booking", "Viajes")
        put("despegar", "Viajes")
        put("trivago", "Viajes")
        put("expedia", "Viajes")
        put("hostal", "Viajes")
        put("resort", "Viajes")
        put("equipaje", "Viajes")
        put("terminal de transporte", "Viajes")
        put("berlinas", "Viajes")
        put("bolivariano", "Viajes")
        put("copetran", "Viajes")
        put("brasilia", "Viajes")
        put("expreso palmira", "Viajes")

        put("gimnasio", "Gimnasio y Deporte")
        put("gym", "Gimnasio y Deporte")
        put("smartfit", "Gimnasio y Deporte")
        put("pesas", "Gimnasio y Deporte")
        put("suplementos", "Gimnasio y Deporte")
        put("proteina", "Gimnasio y Deporte")
        put("creatina", "Gimnasio y Deporte")
        put("bodytech", "Gimnasio y Deporte")
        put("spinning center", "Gimnasio y Deporte")
        put("stark", "Gimnasio y Deporte")
        put("action fitness", "Gimnasio y Deporte")
        put("animalx", "Gimnasio y Deporte")
        put("fit for all", "Gimnasio y Deporte")
        put("crossfit", "Gimnasio y Deporte")
        put("deporte", "Gimnasio y Deporte")
        put("decathlon", "Gimnasio y Deporte")
        put("sportline", "Gimnasio y Deporte")
        put("natacion", "Gimnasio y Deporte")
        put("piscina", "Gimnasio y Deporte")
        put("ropa deportiva", "Gimnasio y Deporte")

        put("regalo", "Regalos")
        put("detalle", "Regalos")
        put("cumpleaños", "Regalos")
        put("aniversario", "Regalos")
        put("flores", "Regalos")
        put("chocolates", "Regalos")
        put("floristeria", "Regalos")
        put("peluche", "Regalos")
        put("sorpresa", "Regalos")
        put("ancheta", "Regalos")

        put("celular nuevo", "Tecnología")
        put("computador", "Tecnología")
        put("pc", "Tecnología")
        put("audifonos", "Tecnología")
        put("cable", "Tecnología")
        put("cargador", "Tecnología")
        put("samsung", "Tecnología")
        put("xiaomi", "Tecnología")
        put("rtx", "Tecnología")
        put("alkosto", "Tecnología")
        put("ktronix", "Tecnología")
        put("mac center", "Tecnología")
        put("ishop", "Tecnología")
        put("tecnologia", "Tecnología")
        put("celular", "Tecnología")
        put("iphone", "Tecnología")
        put("ipad", "Tecnología")
        put("macbook", "Tecnología")
        put("lenovo", "Tecnología")
        put("hp", "Tecnología")
        put("asus", "Tecnología")
        put("acer", "Tecnología")
        put("dell", "Tecnología")
        put("nintendo switch", "Tecnología")
        put("unilago", "Tecnología")
        put("monterrey", "Tecnología")
        put("centro alta tecnologia", "Tecnología")
        put("gamer", "Tecnología")
        put("tigertech", "Tecnología")

        put("bar", "Ocio Nocturno")
        put("cerveza", "Ocio Nocturno")
        put("pola", "Ocio Nocturno")
        put("polas", "Ocio Nocturno")
        put("guaro", "Ocio Nocturno")
        put("aguardiente", "Ocio Nocturno")
        put("ron", "Ocio Nocturno")
        put("discoteca", "Ocio Nocturno")
        put("fiesta", "Ocio Nocturno")
        put("rumba", "Ocio Nocturno")
        put("farra", "Ocio Nocturno")
        put("putas", "Ocio Nocturno")
        put("prostitutas", "Ocio Nocturno")
        put("cariñosas", "Ocio Nocturno")
        put("prepagos", "Ocio Nocturno")
        put("motel", "Ocio Nocturno")
        put("amanecedero", "Ocio Nocturno")
        put("club", "Ocio Nocturno")
        put("tequila", "Ocio Nocturno")
        put("vodka", "Ocio Nocturno")
        put("coctel", "Ocio Nocturno")
        put("tragos", "Ocio Nocturno")
        put("licor", "Ocio Nocturno")
        put("licorera", "Ocio Nocturno")
        put("estanco", "Ocio Nocturno")
    }

    fun suggestCategory(description: String): String? {
        val lowerDesc = description.lowercase(Locale.getDefault())

        val sortedKeywords = keywords.entries.sortedByDescending { it.key.length }

        for ((word, categoryName) in sortedKeywords) {
            if (lowerDesc.contains(word)) {
                return categoryName
            }
        }

        if (lowerDesc.startsWith("para ") ||
            lowerDesc.startsWith("de ") ||
            lowerDesc.startsWith("pago en ") ||
            lowerDesc.startsWith("envio ") ||
            lowerDesc.startsWith("recibi ") ||
            lowerDesc.startsWith("pago a ")) {
            return "Transferencias"
        }

        return null
    }

    fun getCategoryIdByName(name: String): Long {
        val categories = getDefaultCategories()
        val index = categories.indexOfFirst { it.nombre == name }
        return if (index != -1) (index + 1).toLong() else 21L
    }

    fun getDefaultCategories(): List<Categoria> {
        return listOf(
            Categoria(nombre = "Salario e Ingresos", emoji = "💰", colorHex = "#388E3C"),
            Categoria(nombre = "Motos", emoji = "🏍️", colorHex = "#E64A19"),
            Categoria(nombre = "Carros", emoji = "🚗", colorHex = "#1976D2"),
            Categoria(nombre = "Mantenimiento y Reparación", emoji = "🛠️", colorHex = "#5D4037"),
            Categoria(nombre = "Bancos y Finanzas", emoji = "🏦", colorHex = "#009688"),
            Categoria(nombre = "Comida y Restaurantes", emoji = "🍔", colorHex = "#FF9800"),
            Categoria(nombre = "Supermercado", emoji = "🛒", colorHex = "#4CAF50"),
            Categoria(nombre = "Transporte Público", emoji = "🚌", colorHex = "#03A9F4"),
            Categoria(nombre = "Vehículo y Gasolina", emoji = "⛽", colorHex = "#607D8B"),
            Categoria(nombre = "Ocio Nocturno", emoji = "🔞", colorHex = "#B71C1C"),
            Categoria(nombre = "Cine y Entretenimiento", emoji = "🎬", colorHex = "#673AB7"),
            Categoria(nombre = "Salud y Farmacia", emoji = "💊", colorHex = "#E91E63"),
            Categoria(nombre = "Hogar y Servicios", emoji = "🏠", colorHex = "#795548"),
            Categoria(nombre = "Ropa y Cuidado", emoji = "🛍️", colorHex = "#9C27B0"),
            Categoria(nombre = "Educación", emoji = "📚", colorHex = "#00BCD4"),
            Categoria(nombre = "Mascotas", emoji = "🐶", colorHex = "#FF5722"),
            Categoria(nombre = "Viajes", emoji = "✈️", colorHex = "#3F51B5"),
            Categoria(nombre = "Gimnasio y Deporte", emoji = "🏋️", colorHex = "#8BC34A"),
            Categoria(nombre = "Regalos", emoji = "🎁", colorHex = "#FFC107"),
            Categoria(nombre = "Tecnología", emoji = "💻", colorHex = "#607D8B"),
            Categoria(nombre = "Otros", emoji = "📦", colorHex = "#9E9E9E"),
            Categoria(nombre = "Servicios Digitales", emoji = "🌐", colorHex = "#2196F3"),
            Categoria(nombre = "Compras Online", emoji = "📦", colorHex = "#FF5722"),
            Categoria(nombre = "Transferencias", emoji = "💸", colorHex = "#009688")
        )
    }
}