package com.example.finance_code.ui.transaction

object CategorySuggester {
    private val keywords = mapOf(
        "restaurante" to "Comida y Restaurantes",
        "almuerzo" to "Comida y Restaurantes",
        "cena" to "Comida y Restaurantes",
        "desayuno" to "Comida y Restaurantes",
        "pizza" to "Comida y Restaurantes",
        "hamburguesa" to "Comida y Restaurantes",
        "empanada" to "Comida y Restaurantes",
        "empanadas" to "Comida y Restaurantes",
        "corrientazo" to "Comida y Restaurantes",
        "asado" to "Comida y Restaurantes",
        "pollo" to "Comida y Restaurantes",
        "domicilio" to "Comida y Restaurantes",
        "rappi" to "Comida y Restaurantes",

        "mercado" to "Supermercado",
        "d1" to "Supermercado",
        "ara" to "Supermercado",
        "exito" to "Supermercado",
        "carulla" to "Supermercado",
        "jumbo" to "Supermercado",
        "despensa" to "Supermercado",

        "bus" to "Transporte Público",
        "transmilenio" to "Transporte Público",
        "pasaje" to "Transporte Público",
        "sitp" to "Transporte Público",
        "taxi" to "Transporte Público",
        "uber" to "Transporte Público",
        "didi" to "Transporte Público",
        "cabify" to "Transporte Público",
        "picap" to "Transporte Público",

        "gasolina" to "Vehículo y Gasolina",
        "tanqueo" to "Vehículo y Gasolina",
        "mecanico" to "Vehículo y Gasolina",
        "taller" to "Vehículo y Gasolina",
        "parqueadero" to "Vehículo y Gasolina",
        "peaje" to "Vehículo y Gasolina",
        "soat" to "Vehículo y Gasolina",
        "lavadero" to "Vehículo y Gasolina",
        "montallantas" to "Vehículo y Gasolina",
        "arreglo del carro" to "Vehículo y Gasolina",

        "bar" to "Ocio Nocturno",
        "cerveza" to "Ocio Nocturno",
        "pola" to "Ocio Nocturno",
        "polas" to "Ocio Nocturno",
        "guaro" to "Ocio Nocturno",
        "aguardiente" to "Ocio Nocturno",
        "ron" to "Ocio Nocturno",
        "discoteca" to "Ocio Nocturno",
        "fiesta" to "Ocio Nocturno",
        "rumba" to "Ocio Nocturno",
        "farra" to "Ocio Nocturno",
        "putas" to "Ocio Nocturno",
        "prostitutas" to "Ocio Nocturno",
        "cariñosas" to "Ocio Nocturno",
        "prepagos" to "Ocio Nocturno",
        "motel" to "Ocio Nocturno",
        "amanecedero" to "Ocio Nocturno",

        "cine" to "Cine y Entretenimiento",
        "netflix" to "Cine y Entretenimiento",
        "spotify" to "Cine y Entretenimiento",
        "videojuegos" to "Cine y Entretenimiento",
        "play" to "Cine y Entretenimiento",
        "xbox" to "Cine y Entretenimiento",
        "apuestas" to "Cine y Entretenimiento",
        "casino" to "Cine y Entretenimiento",
        "baloto" to "Cine y Entretenimiento",
        "concierto" to "Cine y Entretenimiento",
        "billar" to "Cine y Entretenimiento",
        "tejo" to "Cine y Entretenimiento",
        "sintetica" to "Cine y Entretenimiento",
        "futbol" to "Cine y Entretenimiento",
        "estadio" to "Cine y Entretenimiento",

        "farmacia" to "Salud y Farmacia",
        "medico" to "Salud y Farmacia",
        "pastillas" to "Salud y Farmacia",
        "eps" to "Salud y Farmacia",
        "cita medica" to "Salud y Farmacia",
        "urgencias" to "Salud y Farmacia",
        "condones" to "Salud y Farmacia",
        "preservativos" to "Salud y Farmacia",
        "drogueria" to "Salud y Farmacia",
        "odontologo" to "Salud y Farmacia",
        "dentista" to "Salud y Farmacia",
        "psicologo" to "Salud y Farmacia",
        "terapia" to "Salud y Farmacia",

        "arriendo" to "Hogar y Servicios",
        "agua" to "Hogar y Servicios",
        "luz" to "Hogar y Servicios",
        "gas" to "Hogar y Servicios",
        "internet" to "Hogar y Servicios",
        "claro" to "Hogar y Servicios",
        "movistar" to "Hogar y Servicios",
        "celular" to "Hogar y Servicios",
        "plan" to "Hogar y Servicios",
        "recarga" to "Hogar y Servicios",
        "administracion" to "Hogar y Servicios",
        "aseo" to "Hogar y Servicios",
        "ferreteria" to "Hogar y Servicios",
        "mantenimiento" to "Hogar y Servicios",

        "ropa" to "Ropa y Cuidado",
        "zapatos" to "Ropa y Cuidado",
        "tenis" to "Ropa y Cuidado",
        "chaqueta" to "Ropa y Cuidado",
        "pantalon" to "Ropa y Cuidado",
        "camisa" to "Ropa y Cuidado",
        "centro comercial" to "Ropa y Cuidado",
        "maquillaje" to "Ropa y Cuidado",
        "barberia" to "Ropa y Cuidado",
        "peluqueria" to "Ropa y Cuidado",
        "uñas" to "Ropa y Cuidado",
        "perfume" to "Ropa y Cuidado",

        "universidad" to "Educación",
        "semestre" to "Educación",
        "cuadernos" to "Educación",
        "fotocopias" to "Educación",
        "libros" to "Educación",
        "pension" to "Educación",
        "colegio" to "Educación",
        "utiles" to "Educación",
        "matricula" to "Educación",
        "curso" to "Educación",

        "perro" to "Mascotas",
        "gato" to "Mascotas",
        "veterinario" to "Mascotas",
        "purina" to "Mascotas",
        "concentrado" to "Mascotas",
        "croquetas" to "Mascotas",
        "mascota" to "Mascotas",

        "vuelo" to "Viajes",
        "avion" to "Viajes",
        "hotel" to "Viajes",
        "viaje" to "Viajes",
        "vacaciones" to "Viajes",
        "turismo" to "Viajes",

        "gimnasio" to "Gimnasio y Deporte",
        "gym" to "Gimnasio y Deporte",
        "smartfit" to "Gimnasio y Deporte",
        "pesas" to "Gimnasio y Deporte",
        "suplementos" to "Gimnasio y Deporte",
        "proteina" to "Gimnasio y Deporte",
        "creatina" to "Gimnasio y Deporte",

        "regalo" to "Regalos",
        "detalle" to "Regalos",
        "cumpleaños" to "Regalos",
        "aniversario" to "Regalos",
        "flores" to "Regalos",
        "chocolates" to "Regalos",

        "celular nuevo" to "Tecnología",
        "computador" to "Tecnología",
        "pc" to "Tecnología",
        "audifonos" to "Tecnología",
        "cable" to "Tecnología",
        "cargador" to "Tecnología",
        "apple" to "Tecnología",
        "samsung" to "Tecnología"
    )

    fun suggestCategory(description: String): String? {
        val lowerDesc = description.lowercase()
        for ((word, categoryName) in keywords) {
            if (lowerDesc.contains(word)) {
                return categoryName
            }
        }
        return null
    }
}